azureKeyVaultToKubernetes:
  envInjectorEnabled: false
  vaults:
    - vaultName: Introspectusapi
      objects:
        - query: Tentants
          secretName: regis-api-sql-connectionstrings
          envName: Tentants
        - query: RegisBermudaDBConnection
          secretName: regis-api-sql-connectionstrings
          envName: ConnectionStrings__RegisBermudaDBConnection
        - query: RegisMorristownDBConnection
          secretName: regis-api-sql-connectionstrings
          envName: ConnectionStrings__RegisMorristownDBConnection
        - query: RegisBermudaSysAdminDBConnection
          secretName: regis-api-sql-connectionstrings
          envName: ConnectionStrings__RegisBermudaSysAdminDBConnection
        - query: RegisMorristownSysAdminDBConnection
          secretName: regis-api-sql-connectionstrings
          envName: ConnectionStrings__RegisMorristownSysAdminDBConnection
        - query: RegisSysAdmin_Introspectusapi_BDA
          secretName: regis-api-sql-connectionstrings
          envName: ConnectionStrings__RegisSysAdmin_Introspectusapi_BDA
        - query: RegisSysAdmin_Introspectusapi_BDASB
          secretName: regis-api-sql-connectionstrings
          envName: ConnectionStrings__RegisSysAdmin_Introspectusapi_BDASB 
        - query: RegisSysAdmin_Introspectusapi_US
          secretName: regis-api-sql-connectionstrings
          envName: ConnectionStrings__RegisSysAdmin_Introspectusapi_US 
        - query: Regis_Introspectusapi_BDA
          secretName: regis-api-sql-connectionstrings
          envName: ConnectionStrings__Regis_Introspectusapi_BDA
        - query: Regis_Introspectusapi_BDASB
          secretName: regis-api-sql-connectionstrings
          envName: ConnectionStrings__Regis_Introspectusapi_BDASB 
        - query: Regis_Introspectusapi_US
          secretName: regis-api-sql-connectionstrings
          envName: ConnectionStrings__Regis_Introspectusapi_US 
        - query: RedisCacheConnection
          secretName: regis-api-sql-connectionstrings
          envName: ConnectionStrings__RedisCacheConnection
        - query: AzureRedisCacheConnection
          secretName: regis-api-sql-connectionstrings
          envName: ConnectionStrings__AzureRedisCacheConnection
        - query: CacheType
          secretName: regis-api-appsettings-cache
          envName: CacheType
        - query: SwaggerPrefix
          secretName: regis-api-cessions-appsettings
          envName: Swagger__SwaggerPrefix  
        - query: SwaggerBasePath
          secretName: regis-api-cessions-appsettings
          envName: Swagger__SwaggerBasePath
        - query: ApiKey
          secretName: regis-api-cessions-appsettings
          envName: ApiKey
