{{- $root := . }}
{{- $envInjectionEnabled := $root.Values.azureKeyVaultToKubernetes.envInjectorEnabled }}
{{- range $keyVault := .Values.azureKeyVaultToKubernetes.vaults }}
{{- range $object := $keyVault.secrets }}
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: {{ $object.name }}
  namespace: {{ $root.Release.Namespace | default "default" }}
spec:
  vault:
    name: {{ $keyVault.vaultName }} # name of key vault
    object:
      type: {{ $object.type }} # object type
      name: {{ $object.vaultObject }} # name of the object
      contentType: {{ $object.contentType}}
  {{- if not $envInjectionEnabled }}
  output:
    secret:
      name: {{ $object.name }}-secret
  {{- end }}
---
{{- end }}
{{- end }}